# SAM Configuration for Unified API
version = 0.1

[default.global.parameters]
stack_name = "emp-backend-unified"

[default.build.parameters]
cached = true
parallel = true

[default.validate.parameters]
lint = true

[default.deploy.parameters]
template_file = "template.yaml"
capabilities = "CAPABILITY_NAMED_IAM"
confirm_changeset = true
resolve_s3 = true
stack_name = "emp-backend-unified"
s3_prefix = "emp-backend-unified"
region = "ap-south-1"
disable_rollback = false
image_repositories = []

[default.package.parameters]
resolve_s3 = true

[default.sync.parameters]
watch = true

[default.local_start_api.parameters]
warm_containers = "EAGER"

[default.local_start_lambda.parameters]
warm_containers = "EAGER"