# More information about the configuration file can be found here:
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-config.html
version = 0.1

[default.global.parameters]
stack_name = "emp-backend"

[default.build.parameters]
cached = true
parallel = true

[default.validate.parameters]
lint = true

[default.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
resolve_s3 = true
stack_name = "emp-backend"
s3_prefix = "emp-backend"
region = "ap-south-1"
disable_rollback = true

parameter_overrides = "DBHOST=\"dms.c5g64064s955.ap-south-1.rds.amazonaws.com\" DBNAME=\"DMS_TEST\" DBUSER=\"dmsdatabase\" DBPASSWORD=\"teamtech#2k25\" DBPORT=\"3306\""
#parameter_overrides = "DBHOST=\"ka-devops.crqw00kkqjni.ap-south-1.rds.amazonaws.com\" DBNAME=\"khana_prod\" DBUSER=\"kaprod\" DBPASSWORD=\"Khana2020\" DBPORT=\"3306\""
image_repositories = []


[default.package.parameters]
resolve_s3 = true

[default.sync.parameters]
watch = true

[default.local_start_api.parameters]
warm_containers = "EAGER"

[default.local_start_lambda.parameters]
warm_containers = "EAGER"
